using System.Text.Json;

namespace ConstructionCrew.HomeOffice;

/// <summary>
/// What a provider needs in order to reach the Home Office: the config file written
/// for it, plus the ProviderOptions entries to stamp onto every Foreman running that
/// provider. The options differ per CLI because the CLIs differ -- Claude Code and
/// Copilot take a config file path, Codex has no config-file flag at all and takes the
/// server URL as a `-c` TOML override instead.
/// </summary>
public sealed record McpWiring(string ConfigPath, IReadOnlyDictionary<string, string> ProviderOptions);

/// <summary>
/// Writes the config that points a hired CLI at the Home Office, one writer per
/// ProviderId. Each shape was verified against the real CLI rather than assumed:
///
/// - claude:  `--mcp-config &lt;file&gt;` with {"mcpServers":{...}} -- verified 2026-08-28
///            via a scratch `claude mcp add --transport http` probe.
/// - codex:   `[mcp_servers.&lt;name&gt;] url = "..."` in TOML -- verified by running
///            `codex mcp add cc_probe --url ...` and reading ~/.codex/config.toml back.
///            Codex has no file flag, so the URL also rides in as a `-c` override.
/// - copilot: `--additional-mcp-config @&lt;file&gt;` with
///            {"mcpServers":{"&lt;name&gt;":{"type":"http","url":"..."}}} -- shape read out
///            of the CLI's own bundled validation schema, not guessed.
/// </summary>
public static class McpConfigWriter
{
    /// <summary>The MCP server name every provider registers the Home Office under.</summary>
    public const string HomeOfficeServerName = "home_office";

    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };

    /// <summary>
    /// Writes the right config for <paramref name="providerId"/>, or returns null for a
    /// provider whose MCP shape has not been verified. Never throws on an unknown
    /// provider: an unwired provider is still usable, it just cannot call Home Office
    /// tools, and that is a warning rather than a startup failure.
    /// </summary>
    public static McpWiring? Write(string providerId, string generatedConfigDirectory, Uri homeOfficeBaseAddress) =>
        providerId.ToLowerInvariant() switch
        {
            "claude" => WriteClaudeCodeConfig(generatedConfigDirectory, homeOfficeBaseAddress),
            "codex" => WriteCodexConfig(generatedConfigDirectory, homeOfficeBaseAddress),
            "copilot" => WriteCopilotConfig(generatedConfigDirectory, homeOfficeBaseAddress),
            _ => null,
        };

    public static McpWiring WriteClaudeCodeConfig(string generatedConfigDirectory, Uri homeOfficeBaseAddress, string fileName = "claude-mcp-config.json")
    {
        var mcpUrl = McpUrl(homeOfficeBaseAddress);

        var document = new
        {
            mcpServers = new Dictionary<string, object>
            {
                [HomeOfficeServerName] = new
                {
                    type = "http",
                    url = mcpUrl,
                },
            },
        };

        var path = WriteFile(generatedConfigDirectory, fileName, JsonSerializer.Serialize(document, JsonOptions));
        return new McpWiring(path, new Dictionary<string, string> { ["mcpConfigPath"] = path });
    }

    /// <summary>
    /// Codex's MCP servers live in TOML, and it has no flag that points at an
    /// alternate config file -- so this file is written as the human-readable record
    /// of what got wired (and as something that can be pasted into
    /// $CODEX_HOME/config.toml), while the URL is what actually reaches the CLI, via
    /// CodexProvider's `-c mcp_servers.home_office.url="..."` override.
    /// </summary>
    public static McpWiring WriteCodexConfig(string generatedConfigDirectory, Uri homeOfficeBaseAddress, string fileName = "codex-mcp-config.toml")
    {
        var mcpUrl = McpUrl(homeOfficeBaseAddress);

        var toml = $"""
            # Generated by ConstructionCrew. Matches exactly what `codex mcp add` writes.
            [mcp_servers.{HomeOfficeServerName}]
            url = "{mcpUrl}"

            """;

        var path = WriteFile(generatedConfigDirectory, fileName, toml);
        return new McpWiring(path, new Dictionary<string, string>
        {
            ["mcpServerUrl"] = mcpUrl,
            ["mcpConfigPath"] = path,
        });
    }

    public static McpWiring WriteCopilotConfig(string generatedConfigDirectory, Uri homeOfficeBaseAddress, string fileName = "copilot-mcp-config.json")
    {
        var mcpUrl = McpUrl(homeOfficeBaseAddress);

        var document = new
        {
            mcpServers = new Dictionary<string, object>
            {
                // Copilot's schema requires the server name to be alphanumeric,
                // underscores and hyphens only -- "home_office" qualifies.
                [HomeOfficeServerName] = new
                {
                    type = "http",
                    url = mcpUrl,
                },
            },
        };

        var path = WriteFile(generatedConfigDirectory, fileName, JsonSerializer.Serialize(document, JsonOptions));
        return new McpWiring(path, new Dictionary<string, string> { ["mcpConfigPath"] = path });
    }

    private static string McpUrl(Uri homeOfficeBaseAddress) => new Uri(homeOfficeBaseAddress, "mcp").ToString();

    private static string WriteFile(string generatedConfigDirectory, string fileName, string content)
    {
        Directory.CreateDirectory(generatedConfigDirectory);
        var path = Path.Combine(generatedConfigDirectory, fileName);
        File.WriteAllText(path, content);
        return path;
    }
}
